Fix build error
+ apk add --no-cache --virtual .run-deps ca-certificates openssl pcre zlib libxslt gd geoip perl gettext python py-pip
fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  py-pip (virtual):
    provided by: py2-pip
    required by: